version: '2.3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server Puma -p 3000 -b '0.0.0.0'
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db

volumes:
  db-data:
  gems:
